### ISSUE TITLE
Question About Running Code with Pre-Obtained Singularity Graph on Tetmesh

### ISSUE THREAD

**Issue by herain520** [HendrikBrueckler/QGP3D#5]
I have obtained a globally meshable singularity graph on a tetmesh, which I would like to use as the initial input. However, I currently don't have a frame field on the tetmesh. Could you please let me know if it's possible to run your code with this input? If so, could you kindly guide me on how to adapt your code to work with the singularity graph I already have?

I would be very grateful for your assistance.

Thank you for your time.

Best regards,

**Comment by HendrikBrueckler** [comment]
Hi, sorry for taking so long to get around to this.

QGP3D really only handles the quantization part of the pipeline, which requires an initial seamless parametrization on the input volume.
I think your best bet is to go with [AlgoHex](https://github.com/cgg-bern/AlgoHex) which is an implementation of the entire frame based hexahedral meshing pipeline. It uses QGP3D for quantization internally, but can also be used to compute an intermediate file (a seamless parametrization) in the format that QGP3D (as a standalone) could read.
